### ISSUE TITLE
Question about the widget

### ISSUE THREAD

**Issue by 6clicks** [majulvez/weather-forecast#1]
HI I would like to embed your widget in my fragement. 

the liferay doc said that we had to add @component   `com.liferay.fragment.entry.processor.portlet.alias=app-name`

and then we can add it with:

```
 <lfr-widget-app-name>
</lfr-widget-app-name>

```

I try some names but I can't figured to do it? have you the name I have to use? 
thank's a lot

**Comment by majulvez** [comment]
Hi @6clicks ,

the widget is not ready for that kind of use. It's more than 3 years old and fragments are newer.

You could get it done making a fork of this repo and adding that osgi property with the 'app-name' that you want

https://github.com/majulvez/weather-forecast/blob/master/modules/forecast/src/main/java/com/miguelangeljulvez/forecast/portlet/WeatherPortlet.java#L28

Best regards

**Comment by majulvez** [comment]
I've updated this app to make it liferay 7.3 compatible and I put the property
com.liferay.fragment.entry.processor.portlet.alias=weather-forecast

I can't upload it to the marketplace because liferay 7.3 is not available yet in the list to update this app. When it is available I will
